databases:
  - name: mysite
    plan: free
    region: frankfurt
    databaseName: mysite
    user: mysite

services:
  - type: redis
    plan: free
    name: sidekiq-redis
    region: frankfurt
    maxmemoryPolicy: noeviction
    ipAllowList: [ ] # only allow internal connections
#  - type: worker
#    plan: free
#    name: sidekiq-worker
#    env: ruby
#    region: frankfurt
#    buildCommand: bundle install
#    startCommand: bundle exec sidekiq
#    envVars:
#      - key: REDIS_URL
#        fromService:
#          type: redis
#          name: sidekiq-redis
#          property: connectionString
#      - key: RAILS_MASTER_KEY
#        sync: false
  - type: web
    plan: free
    name: scheduled-tweets
    env: ruby
    region: frankfurt
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false